### ISSUE TITLE
Las notas en las transiciones, porque son las que cambian el estado

### ISSUE THREAD

**Issue by mmasias** [pablarce/23-24-IdSw1-SDR#24]
https://github.com/pablarce/23-24-IdSw1-SDR/blob/5c38a2d62916defb15b9beb5df38b52772d6d6bd/CasosDeUso/CduDetallados/CduNotficaciones/ActualizarNotificacions.puml#L1

![image](https://github.com/pablarce/23-24-IdSw1-SDR/assets/8528047/cea0aaa2-59d6-44d7-a894-35c780ddafff)

```
@startuml

[*] --> VerNotificaciones
note on link
 El <b>administrador</b> solicita ver sus notificaciones

 El <b>sistema</b> muestra las notificaciones
end note

VerNotificaciones --> SeleccionarNotificacion

note on link
 El <b>sistema</b> permite seleccionar notificaciones
 
 El <b>administrador</b> selecciona la notificación que desea actualizar
end note

state condicional <<choice>>

SeleccionarNotificacion --> condicional

note on link
 El <b>administrador</b> ingresa la actualización de la notificación
 
 - Fecha
 - Hora
 -  bla bla bla
end note




condicional --> ConfirmarActualizacion 
note on link
El <b>sistema</b> confirma al administrador que la 
 actualización se ha realizado con éxito
end note

condicional -[#red]-> [*]
note on link
**Error de Actualización:**
El <b>sistema</b> muestra un error 
si no se puede actualizar la notificación
y se le recomienda intentarlo más tarde
end note


ConfirmarActualizacion --> [*]
@enduml
```

**Comment by mmasias** [comment]
@pablarce ¿No han visto esto que les envié el miércoles?

**Comment by pablarce** [comment]
Buenas noches, si ya estuvimos trabajando en ello durante el finde. Para mañana debería estar listo para revisar.

Un saludo, muchas gracias

________________________________
De: Manuel Masías ***@***.***>
Enviado: domingo, junio 23, 2024 11:09:08 p. m.
Para: pablarce/23-24-IdSw1-SDR ***@***.***>
CC: pablarce ***@***.***>; Mention ***@***.***>
Asunto: Re: [pablarce/23-24-IdSw1-SDR] Las notas en las transiciones, porque son las que cambian el estado (Issue #24)


@pablarce<https://github.com/pablarce> ¿No han visto esto que les envié el miércoles?

**Comment by pablarce** [comment]
Los diagramas ya se encuentran corregidos en main
